declare module "@hugeicons/core-free-icons/ArrowRight01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/ArrowDown01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/DropperIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Cancel01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Copy01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Menu01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/CircleIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/ComputerIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Sun01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Moon01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/DashboardCircleIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/LibraryIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Clock01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/StarIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Settings01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/PlusSignIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/ArrowLeft01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/ArrowUp01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Search01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Loading01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/UserGroupIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/LockIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Mail01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Notification01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Shield01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/PaintBrush01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/BulbIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Rocket01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/FavouriteIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/PaintBrush02Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/BrainIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/GlobeIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/UserIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Image01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Link01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Tick02Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/ArrowReloadHorizontalIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/Home01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/BubbleChatIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/InboxIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/PencilEdit01Icon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/NextIcon" { const i: any; export default i; }
declare module "@hugeicons/core-free-icons/ArrowMoveDownRightIcon" { const i: any; export default i; }
